// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cat.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetMyCatMessage struct {
	TargetCat            string   `protobuf:"bytes,1,opt,name=target_cat,json=targetCat,proto3" json:"target_cat,omitempty"`
	//XXX_NoUnkeyedLiteral struct{} `json:"-"`
	//XXX_unrecognized     []byte   `json:"-"`
	//XXX_sizecache        int32    `json:"-"`
}

func (m *GetMyCatMessage) Reset()         { *m = GetMyCatMessage{} }
func (m *GetMyCatMessage) String() string { return proto.CompactTextString(m) }
func (*GetMyCatMessage) ProtoMessage()    {}
func (*GetMyCatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0a5ac8640cab35d, []int{0}
}

func (m *GetMyCatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMyCatMessage.Unmarshal(m, b)
}
func (m *GetMyCatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMyCatMessage.Marshal(b, m, deterministic)
}
func (m *GetMyCatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMyCatMessage.Merge(m, src)
}
func (m *GetMyCatMessage) XXX_Size() int {
	return xxx_messageInfo_GetMyCatMessage.Size(m)
}
func (m *GetMyCatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMyCatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetMyCatMessage proto.InternalMessageInfo

func (m *GetMyCatMessage) GetTargetCat() string {
	if m != nil {
		return m.TargetCat
	}
	return ""
}

type MyCatResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind                 string   `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	//XXX_NoUnkeyedLiteral struct{} `json:"-"`
	//XXX_unrecognized     []byte   `json:"-"`
	//XXX_sizecache        int32    `json:"-"`
}

func (m *MyCatResponse) Reset()         { *m = MyCatResponse{} }
func (m *MyCatResponse) String() string { return proto.CompactTextString(m) }
func (*MyCatResponse) ProtoMessage()    {}
func (*MyCatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0a5ac8640cab35d, []int{1}
}

func (m *MyCatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyCatResponse.Unmarshal(m, b)
}
func (m *MyCatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyCatResponse.Marshal(b, m, deterministic)
}
func (m *MyCatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyCatResponse.Merge(m, src)
}
func (m *MyCatResponse) XXX_Size() int {
	return xxx_messageInfo_MyCatResponse.Size(m)
}
func (m *MyCatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MyCatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MyCatResponse proto.InternalMessageInfo

func (m *MyCatResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MyCatResponse) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

type GetMyCatsMessage struct {
	TargetCats           []string `protobuf:"bytes,1,rep,name=target_cats,json=targetCats,proto3" json:"target_cats,omitempty"`
	//XXX_NoUnkeyedLiteral struct{} `json:"-"`
	//XXX_unrecognized     []byte   `json:"-"`
	//XXX_sizecache        int32    `json:"-"`
}

func (m *GetMyCatsMessage) Reset()         { *m = GetMyCatsMessage{} }
func (m *GetMyCatsMessage) String() string { return proto.CompactTextString(m) }
func (*GetMyCatsMessage) ProtoMessage()    {}
func (*GetMyCatsMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0a5ac8640cab35d, []int{2}
}

func (m *GetMyCatsMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMyCatsMessage.Unmarshal(m, b)
}
func (m *GetMyCatsMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMyCatsMessage.Marshal(b, m, deterministic)
}
func (m *GetMyCatsMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMyCatsMessage.Merge(m, src)
}
func (m *GetMyCatsMessage) XXX_Size() int {
	return xxx_messageInfo_GetMyCatsMessage.Size(m)
}
func (m *GetMyCatsMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMyCatsMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetMyCatsMessage proto.InternalMessageInfo

func (m *GetMyCatsMessage) GetTargetCats() []string {
	if m != nil {
		return m.TargetCats
	}
	return nil
}

type MyCatsResponse struct {
	MyCat                []*MyCatResponse `protobuf:"bytes,1,rep,name=my_cat,json=myCat,proto3" json:"my_cat,omitempty"`
	//XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	//XXX_unrecognized     []byte           `json:"-"`
	//XXX_sizecache        int32            `json:"-"`
}

func (m *MyCatsResponse) Reset()         { *m = MyCatsResponse{} }
func (m *MyCatsResponse) String() string { return proto.CompactTextString(m) }
func (*MyCatsResponse) ProtoMessage()    {}
func (*MyCatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0a5ac8640cab35d, []int{3}
}

func (m *MyCatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyCatsResponse.Unmarshal(m, b)
}
func (m *MyCatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyCatsResponse.Marshal(b, m, deterministic)
}
func (m *MyCatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyCatsResponse.Merge(m, src)
}
func (m *MyCatsResponse) XXX_Size() int {
	return xxx_messageInfo_MyCatsResponse.Size(m)
}
func (m *MyCatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MyCatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MyCatsResponse proto.InternalMessageInfo

func (m *MyCatsResponse) GetMyCat() []*MyCatResponse {
	if m != nil {
		return m.MyCat
	}
	return nil
}

func init() {
	proto.RegisterType((*GetMyCatMessage)(nil), "GetMyCatMessage")
	proto.RegisterType((*MyCatResponse)(nil), "MyCatResponse")
	proto.RegisterType((*GetMyCatsMessage)(nil), "GetMyCatsMessage")
	proto.RegisterType((*MyCatsResponse)(nil), "MyCatsResponse")
}

func init() { proto.RegisterFile("cat.proto", fileDescriptor_c0a5ac8640cab35d) }

var fileDescriptor_c0a5ac8640cab35d = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x4d, 0x4b, 0x80, 0x40,
	0x10, 0x86, 0x35, 0x4b, 0xda, 0x91, 0xd4, 0xf6, 0x24, 0x42, 0x24, 0x0b, 0x81, 0xa7, 0xa5, 0xf4,
	0xe0, 0x0f, 0xf0, 0xd0, 0xc9, 0xcb, 0xfe, 0x81, 0x98, 0x6c, 0xb1, 0x08, 0x3f, 0x70, 0xe7, 0xe2,
	0xbf, 0x0f, 0x3f, 0x43, 0x6f, 0xb3, 0x2f, 0xf3, 0xf2, 0x3c, 0x3b, 0xc0, 0x6a, 0x24, 0x39, 0x8c,
	0x3d, 0xf5, 0xe2, 0x15, 0x82, 0x77, 0x4d, 0xd5, 0x54, 0x22, 0x55, 0xda, 0x18, 0x6c, 0x34, 0x7f,
	0x02, 0x20, 0x1c, 0x1b, 0x4d, 0x1f, 0x35, 0x52, 0x64, 0x27, 0x76, 0xca, 0x14, 0x5b, 0x93, 0x12,
	0x49, 0x14, 0xf0, 0xb0, 0xac, 0x2b, 0x6d, 0x86, 0xbe, 0x33, 0x9a, 0x73, 0xb8, 0xed, 0xb0, 0xd5,
	0xdb, 0xe6, 0x32, 0xcf, 0xd9, 0xef, 0x4f, 0xf7, 0x15, 0xdd, 0xac, 0xd9, 0x3c, 0x8b, 0x1c, 0xc2,
	0x1d, 0x65, 0x76, 0xd6, 0x33, 0x78, 0xff, 0x2c, 0x13, 0xd9, 0x89, 0x93, 0x32, 0x05, 0x07, 0xcc,
	0x88, 0x02, 0xfc, 0xb5, 0x71, 0xe0, 0x5e, 0xc0, 0x6d, 0xa7, 0x4d, 0xcd, 0x49, 0xbd, 0xcc, 0x97,
	0x27, 0x1d, 0x75, 0xd7, 0xce, 0xcf, 0xec, 0x1b, 0x9c, 0x12, 0x89, 0x4b, 0xb8, 0xdf, 0xa1, 0x3c,
	0x94, 0x97, 0xaf, 0xc6, 0x97, 0xae, 0xb0, 0xf8, 0x1b, 0xb0, 0x43, 0x92, 0x3f, 0xca, 0xab, 0x70,
	0x1c, 0xc8, 0xb3, 0x8e, 0xb0, 0x3e, 0xdd, 0xe5, 0x92, 0xf9, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x64, 0x94, 0x63, 0x8a, 0x56, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CatClient is the client API for Cat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CatClient interface {
	GetMyCat(ctx context.Context, in *GetMyCatMessage, opts ...grpc.CallOption) (*MyCatResponse, error)
	GetMyCats(ctx context.Context, in *GetMyCatsMessage, opts ...grpc.CallOption) (*MyCatsResponse, error)
}

type catClient struct {
	cc *grpc.ClientConn
}

func NewCatClient(cc *grpc.ClientConn) CatClient {
	return &catClient{cc}
}

func (c *catClient) GetMyCat(ctx context.Context, in *GetMyCatMessage, opts ...grpc.CallOption) (*MyCatResponse, error) {
	out := new(MyCatResponse)
	err := c.cc.Invoke(ctx, "/Cat/GetMyCat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catClient) GetMyCats(ctx context.Context, in *GetMyCatsMessage, opts ...grpc.CallOption) (*MyCatsResponse, error) {
	out := new(MyCatsResponse)
	err := c.cc.Invoke(ctx, "/Cat/GetMyCats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatServer is the server API for Cat service.
type CatServer interface {
	GetMyCat(context.Context, *GetMyCatMessage) (*MyCatResponse, error)
	GetMyCats(context.Context, *GetMyCatsMessage) (*MyCatsResponse, error)
}

// UnimplementedCatServer can be embedded to have forward compatible implementations.
type UnimplementedCatServer struct {
}

func (*UnimplementedCatServer) GetMyCat(ctx context.Context, req *GetMyCatMessage) (*MyCatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyCat not implemented")
}
func (*UnimplementedCatServer) GetMyCats(ctx context.Context, req *GetMyCatsMessage) (*MyCatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyCats not implemented")
}

func RegisterCatServer(s *grpc.Server, srv CatServer) {
	s.RegisterService(&_Cat_serviceDesc, srv)
}

func _Cat_GetMyCat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyCatMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServer).GetMyCat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Cat/GetMyCat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServer).GetMyCat(ctx, req.(*GetMyCatMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cat_GetMyCats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyCatsMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServer).GetMyCats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Cat/GetMyCats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServer).GetMyCats(ctx, req.(*GetMyCatsMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Cat",
	HandlerType: (*CatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMyCat",
			Handler:    _Cat_GetMyCat_Handler,
		},
		{
			MethodName: "GetMyCats",
			Handler:    _Cat_GetMyCats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cat.proto",
}
